# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2015-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

addons:
  postgresql: 9.4

notifications:
  email: false

dist: trusty
sudo: false

language: python

matrix:
  fast_finish: true
  allow_failures:
    - env: REQUIREMENTS=devel EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
    - env: REQUIREMENTS=devel EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://root@localhost:3306/invenio"
    - env: REQUIREMENTS=devel EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"

cache:
  - pip

services:
  - mysql
  - postgresql
  - redis

env:
  - REQUIREMENTS=lowest EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
  - REQUIREMENTS=lowest EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://root@localhost:3306/invenio"
  - REQUIREMENTS=lowest EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
  - REQUIREMENTS=release EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
  - REQUIREMENTS=release EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://root@localhost:3306/invenio"
  - REQUIREMENTS=release EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
  - REQUIREMENTS=devel EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
  - REQUIREMENTS=devel EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://root@localhost:3306/invenio"
  - REQUIREMENTS=devel EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"

python:
  - "2.7"
  - "3.5"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e $EXTRAS --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e $EXTRAS --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder -e $EXTRAS --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"
  - "mysql -e 'CREATE DATABASE IF NOT EXISTS invenio;' -uroot"
  - "psql -c 'CREATE DATABASE invenio;' -U postgres"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[${EXTRAS}]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: jirikuncar
  password:
    secure: xSD/XcMnmhBYRqcJbLOPsIFDhMCV48EaeLwNkGW0sQPlTsgm1PtIm6eyedogq2gaKJsOoan20mc1VH4L0P2AGiLuAvuxXUpjr/Zj/QePJ8iCeLoy5Tg1I8VfkUQsBtO9lIRtqg5qUI5u8w6PhfAOXB9JqoBOv5WHpE/zir5fvMKwSG/K8nlk3JD+C3Hi3gWgcdIsr/BPpeB+lqqh4dLVQSDz+42aH553IMCCgZpiXEmQ9w9/IdeUZCHMZgFNyz4HQbxQIXx8SLjKmcA/jwbcWCX4WzawJxgnoGH7HcETh9GjNmcRBDbyRLQiG8Um4hyfMoZ87P5om08FfRSvGKce7Wg8bEcZVGrXy/S1H+Ofh2zYG9pQJ7OHF4qqCaw3vhZ2Vo7f5xqv4e7vl3JyukAzpykTYPacad+87Ob8u74dLiO0fszUnhDOyD8MXlbQo8UlOHRL4sdqHTuNGXE0OXMhlvH1+vCzCKEZYu++2BwnYuzll9bt0JCWynyjuD+INAQrns/8YCjVSzgKJ+KjgpNkdoNznUMoBrah/McuAfww5j17FOUNUZVvjcVM24y1zW905poxoiKqJfI+StPYyZ5uv+o9alkAozeCXDrae9awXGKE4JY2jiua+bZQW0WmH9IJ05/ekY9LeB/C4ga05w7bGaxeNhRoJfkcsjANBlRo9zA=
  distributions: "compile_catalog sdist bdist_wheel"
  on:
    tags: true
    python: "2.7"
